spring:
  rabbitmq:
    host: localhost
    username: analytics_service
    password: password

  data:
    mongodb:
      host: localhost
      username: analytics_service
      password: password
      database: vacancies_db

  datasource:
    url: jdbc:mysql://localhost:3306/analytics_db
    username: analytics_service
    password: password

rabbitmq:
  queue: analytics-builder-scheduled-tasks-queue

server:
  port: 8087

logging:
  level:
    com.example: debug