spring:
  rabbitmq:
    host: 217.25.88.12
    port: 15672
    username: analytics_service
    password: password

  data:
    mongodb:
      host: 217.25.88.12
      port: 27017
      username: analytics_service
      password: password
      database: vacancies_db
      auto-index-creation: true

  datasource:
    url: jdbc:mysql://217.25.88.12:3306/analytics_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: analytics_service
    password: password